package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/Kier85/demo-agent/api/graph/model"
	"github.com/Kier85/demo-agent/api/internal/auth"
)

// UpdateShippingAddress is the resolver for the updateShippingAddress field.
func (r *mutationResolver) UpdateShippingAddress(ctx context.Context, orderID string, address model.AddressInput) (*model.Order, error) {
	o, err := r.Store.UpdateShippingAddress(ctx, auth.FromContext(ctx).CustomerEmail, orderID, address)
	return o, gqlErr(ctx, err)
}

// CreateReorder is the resolver for the createReorder field.
func (r *mutationResolver) CreateReorder(ctx context.Context, orderID string, items []*model.ReorderItemInput, idempotencyKey string) (*model.Order, error) {
	o, err := r.Store.CreateReorder(ctx, auth.FromContext(ctx).CustomerEmail, orderID, items, idempotencyKey)
	return o, gqlErr(ctx, err)
}

// EscalateToHuman is the resolver for the escalateToHuman field.
func (r *mutationResolver) EscalateToHuman(ctx context.Context, input model.EscalationInput) (*model.Escalation, error) {
	e, err := r.Store.Escalate(ctx, auth.FromContext(ctx).CustomerEmail, input)
	return e, gqlErr(ctx, err)
}

// SetAgentStatus is the resolver for the setAgentStatus field.
func (r *mutationResolver) SetAgentStatus(ctx context.Context, provider string, enabled bool, reason string) (*model.AgentStatus, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, gqlErr(ctx, err)
	}
	st, err := r.Store.SetAgentStatus(ctx, provider, enabled, reason)
	return st, gqlErr(ctx, err)
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	o, err := r.Store.Order(ctx, auth.FromContext(ctx).CustomerEmail, id)
	return o, gqlErr(ctx, err)
}

// Shipment is the resolver for the shipment field.
func (r *queryResolver) Shipment(ctx context.Context, orderID string) (*model.Shipment, error) {
	s, err := r.Store.Shipment(ctx, auth.FromContext(ctx).CustomerEmail, orderID)
	return s, gqlErr(ctx, err)
}

// AgentStatus is the resolver for the agentStatus field.
func (r *queryResolver) AgentStatus(ctx context.Context, provider string) (*model.AgentStatus, error) {
	st, err := r.Store.AgentStatus(ctx, provider)
	return st, gqlErr(ctx, err)
}

// Escalations is the resolver for the escalations field.
func (r *queryResolver) Escalations(ctx context.Context, limit *int) ([]*model.Escalation, error) {
	if err := requireAdmin(ctx); err != nil {
		return nil, gqlErr(ctx, err)
	}
	n := 20
	if limit != nil {
		n = *limit
	}
	es, err := r.Store.Escalations(ctx, n)
	return es, gqlErr(ctx, err)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
