// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Address struct {
	Name       string  `json:"name"`
	Line1      string  `json:"line1"`
	Line2      *string `json:"line2,omitempty"`
	City       string  `json:"city"`
	Region     *string `json:"region,omitempty"`
	PostalCode string  `json:"postalCode"`
	Country    string  `json:"country"`
}

type AddressInput struct {
	Name       string  `json:"name"`
	Line1      string  `json:"line1"`
	Line2      *string `json:"line2,omitempty"`
	City       string  `json:"city"`
	Region     *string `json:"region,omitempty"`
	PostalCode string  `json:"postalCode"`
	Country    string  `json:"country"`
}

type AgentStatus struct {
	Provider  string    `json:"provider"`
	Enabled   bool      `json:"enabled"`
	Reason    string    `json:"reason"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Customer struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}

type Escalation struct {
	ID        string             `json:"id"`
	TicketID  string             `json:"ticketId"`
	OrderID   *string            `json:"orderId,omitempty"`
	Category  EscalationCategory `json:"category"`
	Reason    string             `json:"reason"`
	Summary   string             `json:"summary"`
	CreatedAt time.Time          `json:"createdAt"`
}

type EscalationInput struct {
	TicketID string             `json:"ticketId"`
	OrderID  *string            `json:"orderId,omitempty"`
	Category EscalationCategory `json:"category"`
	Reason   string             `json:"reason"`
	Summary  string             `json:"summary"`
}

type Mutation struct {
}

type Order struct {
	ID              string       `json:"id"`
	Status          OrderStatus  `json:"status"`
	CreatedAt       time.Time    `json:"createdAt"`
	TotalCents      int          `json:"totalCents"`
	Currency        string       `json:"currency"`
	Customer        *Customer    `json:"customer"`
	ShippingAddress *Address     `json:"shippingAddress"`
	Items           []*OrderItem `json:"items"`
	// Set when this order was created as a reorder of another order.
	ReorderOf *string `json:"reorderOf,omitempty"`
	// True while the order has not entered production.
	CanChangeAddress bool `json:"canChangeAddress"`
}

type OrderItem struct {
	Sku            string `json:"sku"`
	Product        string `json:"product"`
	Size           string `json:"size"`
	Quantity       int    `json:"quantity"`
	UnitPriceCents int    `json:"unitPriceCents"`
}

type Query struct {
}

type ReorderItemInput struct {
	Sku      string `json:"sku"`
	Quantity int    `json:"quantity"`
}

type Shipment struct {
	OrderID           string           `json:"orderId"`
	Carrier           string           `json:"carrier"`
	TrackingNumber    string           `json:"trackingNumber"`
	Status            ShipmentStatus   `json:"status"`
	ShippedAt         time.Time        `json:"shippedAt"`
	EstimatedDelivery time.Time        `json:"estimatedDelivery"`
	DeliveredAt       *time.Time       `json:"deliveredAt,omitempty"`
	Events            []*TrackingEvent `json:"events"`
}

type TrackingEvent struct {
	At          time.Time `json:"at"`
	Location    string    `json:"location"`
	Description string    `json:"description"`
}

type EscalationCategory string

const (
	EscalationCategoryRefund            EscalationCategory = "REFUND"
	EscalationCategoryDamagedOrMisprint EscalationCategory = "DAMAGED_OR_MISPRINT"
	EscalationCategoryLostOrDelayed     EscalationCategory = "LOST_OR_DELAYED"
	EscalationCategoryPolicyException   EscalationCategory = "POLICY_EXCEPTION"
	EscalationCategoryAmbiguous         EscalationCategory = "AMBIGUOUS"
	EscalationCategoryOther             EscalationCategory = "OTHER"
)

var AllEscalationCategory = []EscalationCategory{
	EscalationCategoryRefund,
	EscalationCategoryDamagedOrMisprint,
	EscalationCategoryLostOrDelayed,
	EscalationCategoryPolicyException,
	EscalationCategoryAmbiguous,
	EscalationCategoryOther,
}

func (e EscalationCategory) IsValid() bool {
	switch e {
	case EscalationCategoryRefund, EscalationCategoryDamagedOrMisprint, EscalationCategoryLostOrDelayed, EscalationCategoryPolicyException, EscalationCategoryAmbiguous, EscalationCategoryOther:
		return true
	}
	return false
}

func (e EscalationCategory) String() string {
	return string(e)
}

func (e *EscalationCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EscalationCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EscalationCategory", str)
	}
	return nil
}

func (e EscalationCategory) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EscalationCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EscalationCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderStatus string

const (
	OrderStatusReceived     OrderStatus = "RECEIVED"
	OrderStatusProofPending OrderStatus = "PROOF_PENDING"
	OrderStatusInProduction OrderStatus = "IN_PRODUCTION"
	OrderStatusShipped      OrderStatus = "SHIPPED"
	OrderStatusDelivered    OrderStatus = "DELIVERED"
	OrderStatusCancelled    OrderStatus = "CANCELLED"
)

var AllOrderStatus = []OrderStatus{
	OrderStatusReceived,
	OrderStatusProofPending,
	OrderStatusInProduction,
	OrderStatusShipped,
	OrderStatusDelivered,
	OrderStatusCancelled,
}

func (e OrderStatus) IsValid() bool {
	switch e {
	case OrderStatusReceived, OrderStatusProofPending, OrderStatusInProduction, OrderStatusShipped, OrderStatusDelivered, OrderStatusCancelled:
		return true
	}
	return false
}

func (e OrderStatus) String() string {
	return string(e)
}

func (e *OrderStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderStatus", str)
	}
	return nil
}

func (e OrderStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ShipmentStatus string

const (
	ShipmentStatusLabelCreated   ShipmentStatus = "LABEL_CREATED"
	ShipmentStatusInTransit      ShipmentStatus = "IN_TRANSIT"
	ShipmentStatusOutForDelivery ShipmentStatus = "OUT_FOR_DELIVERY"
	ShipmentStatusDelivered      ShipmentStatus = "DELIVERED"
	ShipmentStatusException      ShipmentStatus = "EXCEPTION"
)

var AllShipmentStatus = []ShipmentStatus{
	ShipmentStatusLabelCreated,
	ShipmentStatusInTransit,
	ShipmentStatusOutForDelivery,
	ShipmentStatusDelivered,
	ShipmentStatusException,
}

func (e ShipmentStatus) IsValid() bool {
	switch e {
	case ShipmentStatusLabelCreated, ShipmentStatusInTransit, ShipmentStatusOutForDelivery, ShipmentStatusDelivered, ShipmentStatusException:
		return true
	}
	return false
}

func (e ShipmentStatus) String() string {
	return string(e)
}

func (e *ShipmentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShipmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShipmentStatus", str)
	}
	return nil
}

func (e ShipmentStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShipmentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShipmentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
